services:
  memes:
    image: memes_from_reddit:latest
    container_name: memes_from_reddit
    restart: unless-stopped
    ports:
      - "7860:7860"
    environment:
      - PYTHONUNBUFFERED=1
    # volumes:
    #   - ./data:/data
